Remind me later
nextcloud/spreed-ios pull request #1320
Opened 2023-08-03 10:28 UTC by SystemKeeper

Fixes #1313 

<img src="https://github.com/nextcloud/talk-ios/assets/1580193/0e758fb9-88ba-44d8-aff4-e74b6e6f9831" width=250 />

<img src="https://github.com/nextcloud/talk-ios/assets/1580193/8947795a-3bd2-4bad-884d-1df7d886df1f" width=250 />

Notes:
* On the screenshot it says 8am in all cases, but for "Later today" it's 6pm as specified and is correct in code
* Wording might change, waiting for the decision on #1313 about that, but did go with "Next Saturday" and "Next Monday" for now (CC @nimishavijay for the current state)
* When "Today" is already >= 6pm, the option is hidden
* For custom date & time the minimum selectable time would be 15 min in the future (so no reminders in the past)

2023-08-03 11:05 UTC, nickvergessen requested changes
Ref https://github.com/nextcloud/server/issues/39181#issuecomment-1662059862

2023-08-03 11:05 UTC, nickvergessen commented on NextcloudTalk/en.lproj/Localizable.strings
> +"Remind me later" = "Remind me later";
```suggestion
"Set reminder" = "Set reminder";
```

2023-08-03 11:05 UTC, nickvergessen commented on NextcloudTalk/NCChatViewController.m
> +        UIMenu *remindeMeLaterMenu = [UIMenu menuWithTitle:NSLocalizedString(@"Remind me later", @"Remind me later about that message")
```suggestion
        UIMenu *remindeMeLaterMenu = [UIMenu menuWithTitle:NSLocalizedString(@"Set remind", @"Remind me later about that message")
```

2023-08-03 11:11 UTC, SystemKeeper commented
> Ref [nextcloud/server#39181 (comment)](https://github.com/nextcloud/server/issues/39181#issuecomment-1662059862)

Done, updated screenshot:

<img src="https://github.com/nextcloud/talk-ios/assets/1580193/58ac0bfb-c8cc-4138-b741-16bd8deefc97" width=250 />

2023-08-08 20:38 UTC, SystemKeeper commented
Adjusted options as discussed:
<img src="https://github.com/nextcloud/talk-ios/assets/1580193/5b9b7404-58ec-4b80-a3ea-614e6e649f2c" width=250 />

Delete option if a reminder is already available:
<img src="https://github.com/nextcloud/talk-ios/assets/1580193/5acdc21e-882b-466f-b5b3-a69ad3d60597" width=250 />

2023-08-08 21:21 UTC, nickvergessen commented
At least on the backend you could still set the reminder (it gets updated/overwritten) as well as deleting it.
According to https://github.com/nextcloud/server/issues/39181#issuecomment-1664832347 the option would be called "Clear reminder" and below that there are the normal options to set the reminder to a different value.

2023-08-09 06:39 UTC, SystemKeeper commented
Moved to inline menu:
<img src="https://github.com/nextcloud/talk-ios/assets/1580193/71f6f23f-1f5c-4b53-b761-bcc5c38e1602" width=250 />

@nickvergessen ✅?

2023-08-09 06:46 UTC, nickvergessen approved these changes
swift code looks good, other code I can not understand, but seems to do it's job and screenshot is 🤩

2023-08-09 07:56 UTC, merged