Test with 24
nextcloud/spreed-ios pull request #1372
Opened 2023-09-22 11:06 UTC by SystemKeeper

2023-09-22 12:39 UTC, SystemKeeper commented
Well, since 23 does not support reactions, it fails anyway -,- will take a look

2023-09-26 15:23 UTC, Ivansss requested changes

2023-09-26 15:23 UTC, Ivansss commented on .github/workflows/uitests.yml
> +      - extcloudTalkUITests/**
typo?

2023-09-26 15:45 UTC, SystemKeeper commented on .github/workflows/uitests.yml
> +      - extcloudTalkUITests/**
Argh 🙈

2023-09-26 20:46 UTC, SystemKeeper commented on .github/workflows/uitests.yml
> +      - extcloudTalkUITests/**
Fixed and rebased

2023-09-26 21:01 UTC, SystemKeeper commented
Tests failing because of https://github.com/nextcloud/talk-ios/pull/1375/commits/d0d369c59938aad8c4364484b32da999dfec2d9c
Will rebase once 
- https://github.com/nextcloud/talk-ios/pull/1375 

is merged

2023-09-27 09:08 UTC, Ivansss commented
#1375 merged :)

2023-09-27 11:01 UTC, SystemKeeper commented
Rebased and tests passed :)

2023-09-27 11:45 UTC, Ivansss approved these changes

2023-09-27 11:45 UTC, merged