Continuous Voice recording
nextcloud/spreed-ios pull request #1786
Opened 2024-08-30 13:49 UTC by rapterjet2004

- fixes #618 

### Current Demo
https://github.com/user-attachments/assets/97d74ac4-250c-4100-aabc-c90e0694c98a

### ToDo
- [x] Added a voice recording lock button
- [x] Added a new SwiftUI View for expanded voice recording
- [ ] Stop AVAudioRecorder from ending and implement the send, delete, stop/restart buttons

2024-09-08 19:00 UTC, SystemKeeper reviewed
Rotating the screen breaks the UI:
![Simulator Screenshot - iPhone 15 Pro - 2024-09-08 at 20 36 42](https://github.com/user-attachments/assets/b72b63b5-8319-4e01-a2cd-04cae3c180ee)

Also I noticed that the buttons are not clickable in the bottom area?! 🤔 

Please also take care of the swiftlint warnings :)

2024-09-08 19:00 UTC, SystemKeeper commented on NextcloudTalk/BaseChatViewController.swift
> +        })
```suggestion
        let button = UIButton(frame: .init(x: 0, y: 0, width: 44, height: 44))
```

`primaryAction` is nullable, you can just omit it, if it's not used.

2024-09-08 19:00 UTC, SystemKeeper commented on NextcloudTalk/BaseChatViewController.swift
> +    }
```suggestion
    func showExpandedVoiceMessageRecordingView(offset: Int) {
        let expandedView = ExpandedVoiceMessageRecordingView(
            deleteFunc: handleDelete, sendFunc: handleSend, recordFunc: handleRecord(isRecording:), timeElapsed: offset
        )

        let hostingController = UIHostingController(rootView: expandedView)
        guard let expandedVoiceMessageRecordingView = hostingController.view else { return }

        self.expandedUIHostingController = hostingController
        self.textInputbar.addSubview(expandedVoiceMessageRecordingView)

        expandedVoiceMessageRecordingView.translatesAutoresizingMaskIntoConstraints = false

        let views = [
            "expandedVoiceMessageRecordingView": expandedVoiceMessageRecordingView
        ]

        self.textInputbar.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[expandedVoiceMessageRecordingView]|", metrics: nil, views: views))
        self.textInputbar.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[expandedVoiceMessageRecordingView]|", metrics: nil, views: views))
    }
```

This way you don't have to force-unwrap anything.

2024-09-08 19:00 UTC, SystemKeeper commented on NextcloudTalk/BaseChatViewController.swift
> +        print("Delete Handled")
If you want to keep these prints, could you make them a bit more explicit, so it is clear that it's from an audio message?

2024-09-08 19:01 UTC, SystemKeeper commented
Really nice work otherwise, thanks a lot 👍

2024-10-01 16:18 UTC, Ivansss requested changes
Thanks a lot @rapterjet2004 for implementing this nice feature! :)

The PR overall looks good, but there is an issue when the user tries to lock the voice recording when the keyboard is being shown.
The new view to delete/stop/send the recording is hidden under the keyboard and it only appears when hidding the keyboard.


https://github.com/user-attachments/assets/fc25760c-851c-4291-9aa8-0cf940f29bb7

2024-10-09 20:57 UTC, SystemKeeper commented
Something is still weird when trying to click the stop button, it does not work for me:

https://github.com/user-attachments/assets/2cd86cd2-ddb2-49ba-9afb-d2d5159b7ab3

Deleting and sending does work?

Seems the padding is not correct as some icons are covered now:

<img width="332" alt="Bildschirmfoto 2024-10-09 um 22 45 43" src="https://github.com/user-attachments/assets/d337c7d3-acd7-44ba-9e23-87295cf96abe">


I didn't test too much, but maybe something like this is what you want to achieve?

```diff
diff --git a/NextcloudTalk/BaseChatViewController.swift b/NextcloudTalk/BaseChatViewController.swift
index b960f5ad..2b94fe45 100644
--- a/NextcloudTalk/BaseChatViewController.swift
+++ b/NextcloudTalk/BaseChatViewController.swift
@@ -1528,7 +1528,7 @@ import SwiftUI
         guard let expandedVoiceMessageRecordingView = hostingController.view else { return }
 
         self.expandedUIHostingController = hostingController
-        self.textInputbar.addSubview(expandedVoiceMessageRecordingView)
+        self.view.addSubview(expandedVoiceMessageRecordingView)
 
         expandedVoiceMessageRecordingView.translatesAutoresizingMaskIntoConstraints = false
 
@@ -1536,7 +1536,7 @@ import SwiftUI
             "expandedVoiceMessageRecordingView": expandedVoiceMessageRecordingView
         ]
 
-        self.view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|-(>=0)-[expandedVoiceMessageRecordingView]|", metrics: nil, views: views))
+        expandedVoiceMessageRecordingView.bottomAnchor.constraint(equalTo: self.textInputbar.bottomAnchor).isActive = true
         self.view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[expandedVoiceMessageRecordingView]|", metrics: nil, views: views))
     }
```

2024-10-10 09:15 UTC, SystemKeeper commented
> but maybe something like this is what you want to achieve?

You can do a similar thing for left and right anchor as well, if you don't like the visual layout format.

2024-11-05 08:51 UTC, SystemKeeper approved these changes
I still see a few corner-cases here and there, but I think this is fine to do at some point in another PR. From my POV fine to merge. Thanks for the PR 👍

2024-11-05 16:13 UTC, Ivansss approved these changes
Thanks a lot for your work here @rapterjet2004 :)
As @SystemKeeper said, there are small UI issues that could be tackled in a follow-up PR ;)

2024-11-05 16:13 UTC, merged