Changed "Cancel" to "Close" in some dialogs
nextcloud/spreed-ios pull request #1879
Opened 2024-11-15 14:27 UTC by rapterjet2004

- fixes #1781 

Hopefully got them all

2024-11-18 10:00 UTC, Ivansss requested changes

2024-11-18 10:00 UTC, Ivansss commented on NextcloudTalk/QRCodeLoginController.swift
> +                alert.addAction(UIAlertAction(title: NSLocalizedString("Close", comment: ""), style: .cancel, handler: nil))
I would use "OK" for error dialogs when no further action from the user is needed (as we do in other error dialogs in this app).
In this particular case, we could even think of adding a "Settings" button to redirect the user into the app's settings as we do in:
https://github.com/nextcloud/talk-ios/blob/d7eb5acf2c378c94c1311598b22c3389b23ee104/NextcloudTalk/VoiceMessageTranscribeViewController.m#L172

2024-11-18 10:00 UTC, Ivansss commented on NextcloudTalk/PollCreationViewController.swift
> +        alert.addAction(UIAlertAction(title: NSLocalizedString("Close", comment: ""), style: .cancel, handler: nil))
I would use "OK" for error dialogs when no further action from the user is needed (as we do in other error dialogs in this app).

2024-11-18 10:00 UTC, Ivansss commented on NextcloudTalk/SettingsTableViewController.swift
> +        let cancelAction = UIAlertAction(title: NSLocalizedString("Close", comment: ""), style: .default, handler: nil)
I would use "OK" for error dialogs when no further action from the user is needed (as we do in other error dialogs in this app).

2024-11-18 10:00 UTC, Ivansss commented on NextcloudTalk/ShareLocationViewController.m
> +    [alert addAction:[UIAlertAction actionWithTitle:NSLocalizedString(@"Close", nil) style:UIAlertActionStyleCancel handler:nil]];
I would use "OK" for error dialogs when no further action from the user is needed (as we do in other error dialogs in this app).
In this particular case, we could even think of adding a "Settings" button to redirect the user into the app's settings as we do in:
https://github.com/nextcloud/talk-ios/blob/d7eb5acf2c378c94c1311598b22c3389b23ee104/NextcloudTalk/VoiceMessageTranscribeViewController.m#L172

2024-11-18 10:00 UTC, Ivansss commented on NextcloudTalk/VoiceMessageTranscribeViewController.m
> +    [alert addAction:[UIAlertAction actionWithTitle:NSLocalizedString(@"Close", nil)
I would use "OK" for error dialogs when no further action from the user is needed (as we do in other error dialogs in this app).

2024-11-18 20:12 UTC, SystemKeeper commented
Rebased because of deprecated CI action used. Should run now.

2024-11-20 13:11 UTC, Ivansss approved these changes
Thanks a lot for this PR @rapterjet2004 :)

2024-11-20 13:11 UTC, merged