Show user status icon in conversations list
nextcloud/spreed-ios pull request #660
Opened 2021-11-12 11:42 UTC by alazarevic5

Show user status icon in conversations list like in the web Talk app.
When status is everything instead do not disturb and somebody set custom status with emoji  (for e.g. working 💻) , emoji will be shown. In other cases status will be shown (online, away, dnd).

2021-11-14 23:05 UTC, SystemKeeper requested changes
Sorry for being nitpicky about the style 😄

2021-11-14 23:05 UTC, SystemKeeper commented on NextcloudTalk/RoomsTableViewController.m
> +        }
There's something wrong with the indentation here. Also the `else` should be in the same line as closing/opening bracets and have a space around it.
I would  make this a bit shorter, if I'm not mistaken, the following should do the same:

```objective-c
    //Show User Status
    if (room.type == kNCRoomTypeOneToOne && [room.status length] != 0) {
        if (![room.status isEqual:@"dnd"] && [room.statusIcon length] != 0) {
            [cell setUserStatusIcon:room.statusIcon];
        } else {
            [cell setUserStatus:room.status];
        }
    }
```

2021-11-14 23:05 UTC, SystemKeeper commented on NextcloudTalk/RoomTableViewCell.h
> +-(void)setUserStatusIcon:(NSString *)userStatusIcon;
Space before `(void)` to be inline with the other part of the file.

2021-11-14 23:05 UTC, SystemKeeper commented on NextcloudTalk/NCRoom.m
> +    room.status = ([roomDict objectForKey:@"status"] != [NSNull null]) ? [[roomDict objectForKey:@"status"] stringValue] : @"";
I'm not absolutely sure about this one. Do we need to check for `[NSNull null]` here? I would imagine that
`[roomDict objectForKey:@"status"] ? [[roomDict objectForKey:@"status"] stringValue] : @""`

2021-11-14 23:05 UTC, SystemKeeper commented on NextcloudTalk/NCDatabaseManager.m
> +            if (oldSchemaVersion < kTalkDatabaseSchemaVersion) {
Is this just to make it more explicit what's happening here?

2021-11-16 17:01 UTC, alazarevic5 commented on NextcloudTalk/NCRoom.m
> +    room.status = ([roomDict objectForKey:@"status"] != [NSNull null]) ? [[roomDict objectForKey:@"status"] stringValue] : @"";
I am not sure. I kept as it was, for now, because if we do not compare with null, when we receive null for status (for e.g. group conversation), app crashes, because we are trying to use null value.

2021-11-17 10:37 UTC, Ivansss approved these changes

2021-11-17 10:38 UTC, merged