Add deep link url parameter for room token
nextcloud/spreed-ios pull request #671
Opened 2021-11-19 12:13 UTC by thisIsTheFoxe

Allow other apps to open (and join) a specific, already existing room.
If both userId & roomToken are specified, prefer userId.

Usage:
```
nextcloudtalk://open-conversation?server={serverURL}&user={userId}&withUser={userId}

nextcloudtalk://open-conversation?server={serverURL}&user={userId}&withRoomToken={roomToken}
```

## Related
- #656 

## TODO:
- [ ] testing

2021-11-23 11:02 UTC, Ivansss requested changes

2021-11-23 11:02 UTC, Ivansss commented on NextcloudTalk/NCRoomsManager.m
> +    } else if (roomToken != nil) {
We could check `withUser` and `roomToken` as

```
if (withUser) {
    [self joinOrCreateChatWithUser:withUser usingAccountId:accountId];
} else if (roomToken) {
```
same as you did in NCUserInterfaceController.m ;)

2021-11-23 18:24 UTC, Ivansss approved these changes
Tested and works 👍

2021-11-23 18:25 UTC, merged

2024-11-28 23:41 UTC, LexioJ commented
As this ability exists what now would be missing is to have a web landing page (as many other vendors provide) where the user is able to decide to join using their browser (use direct https) or dependent of the current connected platform (win/ios/mac/linux/android) to start the equivalent app protocol handler like nextcloudtalk://open-conversation to start the locally installed app instead. What do you think ? Where to raise this request ?