Handle error while requesting call transaction.
nextcloud/spreed-ios pull request #700
Opened 2022-01-07 15:25 UTC by Ivansss

Starting a call from the chat view using the top right buttons fails some times (usually only on the first try after launching the app)
This causes the call (or videocall) button keeps spinning forever.
This PR resets the call buttons if requesting the call transaction fails.

2022-01-10 18:44 UTC, SystemKeeper requested changes
I receive the following exception when error 7 occurs:

![image](https://user-images.githubusercontent.com/1580193/148821328-4676db83-75b2-402e-9372-757adebb48d4.png)

![image](https://user-images.githubusercontent.com/1580193/148821351-91d630b1-8b4b-412a-852f-e123ae8ad775.png)

2022-01-10 18:56 UTC, SystemKeeper commented
As discussed, looks like this is a timing issue between first initializing CallKit vs. requesting a transaction. In a quick test, the following was enough to make the error 7 disappear:

```obj-c
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.callController requestTransaction:transaction completion:^(NSError * _Nullable error) {
                if (!error) {
                    [weakSelf.calls setObject:call forKey:callUUID];
                } else {
                    NSLog(@"%@", error.localizedDescription);
                    NSDictionary *userInfo = [NSDictionary dictionaryWithObject:token forKey:@"roomToken"];
                    [[NSNotificationCenter defaultCenter] postNotificationName:CallKitManagerDidFailRequestingCallTransaction
                                                                        object:self
                                                                      userInfo:userInfo];
                }
            }];
        });
```

Also tried
`dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^(void)`, which worked as well.

A retry should be added nonetheless in another pr.

2022-01-11 09:51 UTC, Ivansss commented
I just dispatch the layout modification code on the main thread for now.
Still can't trigger the error 7 reliably 😅 but as we discussed we can dispatch the requestTransaction with a small delay and retry if it fails in another PR ;)

2022-01-11 11:23 UTC, SystemKeeper approved these changes

2022-01-11 11:24 UTC, merged